<?php

global $config;
$site = $config["platformTitle"] ?? 'GMI Scores';

return [
  'steps' => [
    [
      'id'     => 'welcome',
      'page'   => 'home',
      'target' => '.home-stats-grid',
      'title'  => __('tutorial_welcome_title', ['site' => $site]),
      'desc'   => __('tutorial_welcome_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'create-game',
      'page'   => 'games',
      'target' => 'a[href="add-game.php"]',
      'title'  => __('tutorial_create_game_title'),
      'desc'   => __('tutorial_create_game_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'add-game-name',
      'page'   => 'add-game',
      'target' => '#name',
      'title'  => __('tutorial_add_game_name_title'),
      'desc'   => __('tutorial_add_game_name_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'add-game-auth',
      'page'   => 'add-game',
      'target' => '#require_player_auth',
      'title'  => __('tutorial_add_game_auth_title'),
      'desc'   => __('tutorial_add_game_auth_desc'),
      'pos'    => 'top',
      'arrow'  => true,
    ],
    [
      'id'         => 'game-id',
      'page'       => 'game',
      'disableBack'=> true,
      'target'     => '#input-gameid',
      'title'      => __('tutorial_game_id_title'),
      'desc'       => __('tutorial_game_id_desc', ['site' => $site]),
      'pos'        => 'bottom',
      'arrow'      => true,
    ],
    [
      'id'         => 'client-secret',
      'page'       => 'game',
      'disableBack'=> true,
      'target'     => '#input-secret',
      'title'      => __('tutorial_client_secret_title'),
      'desc'       => __('tutorial_client_secret_desc'),
      'pos'        => 'bottom',
      'arrow'      => true,
    ],
    [
      'id'         => 'players-tab',
      'page'       => 'game',
      'disableBack'=> true,
      'target'     => '[data-tab="players"]',
      'title'      => __('tutorial_players_tab_title'),
      'desc'       => __('tutorial_players_tab_desc'),
      'pos'        => 'bottom',
      'arrow'      => true,
    ],
    [
      'id'         => 'leaderboard-tab',
      'page'       => 'game',
      'disableBack'=> true,
      'target'     => '[data-tab="leaderboards"]',
      'title'      => __('tutorial_leaderboard_tab_title'),
      'desc'       => __('tutorial_leaderboard_tab_desc'),
      'pos'        => 'bottom',
      'arrow'      => true,
    ],
    [
      'id'         => 'analytics',
      'page'       => 'game',
      'disableBack'=> true,
      'target'     => '[data-tab="analytics"]',
      'title'      => __('tutorial_analytics_title'),
      'desc'       => __('tutorial_analytics_desc'),
      'pos'        => 'bottom',
      'arrow'      => true,
    ],
    [
      'id'     => 'api-submit',
      'page'   => 'documentation',
      'target' => '[data-tab="resources"]',
      'title'  => __('tutorial_api_submit_title'),
      'desc'   => __('tutorial_api_submit_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'complete',
      'page'   => 'home',
      'target' => '.home-stats-grid',
      'title'  => __('tutorial_complete_title'),
      'desc'   => __('tutorial_complete_desc', ['site' => $site]),
      'pos'    => 'bottom',
      'arrow'  => true,
      'final'  => true,
    ],
  ],
];
