<?php

return [
  'steps' => [
    [
      'id'     => 'welcome',
      'page'   => 'home',
      'target' => '.home-stats-grid',
      'title'  => __('tutorial_welcome_title'),
      'desc'   => __('tutorial_welcome_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'create-game',
      'page'   => 'games',
      'target' => 'a[href="add-game.php"]',
      'title'  => __('tutorial_create_game_title'),
      'desc'   => __('tutorial_create_game_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'add-game-name',
      'page'   => 'add-game',
      'target' => '#name',
      'title'  => __('tutorial_add_game_name_title'),
      'desc'   => __('tutorial_add_game_name_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'add-game-auth',
      'page'   => 'add-game',
      'target' => '#require_player_auth',
      'title'  => __('tutorial_add_game_auth_title'),
      'desc'   => __('tutorial_add_game_auth_desc'),
      'pos'    => 'top',
      'arrow'  => true,
    ],
    [
      'id'     => 'game-id',
      'page'   => 'game',
      'target' => '#input-gameid',
      'title'  => __('tutorial_game_id_title'),
      'desc'   => __('tutorial_game_id_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'client-secret',
      'page'   => 'game',
      'target' => '#input-secret',
      'title'  => __('tutorial_client_secret_title'),
      'desc'   => __('tutorial_client_secret_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'leaderboard-tab',
      'page'   => 'game',
      'target' => '[data-tab="leaderboards"]',
      'title'  => __('tutorial_leaderboard_tab_title'),
      'desc'   => __('tutorial_leaderboard_tab_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'analytics',
      'page'   => 'game',
      'target' => '[data-tab="analytics"]',
      'title'  => __('tutorial_analytics_title'),
      'desc'   => __('tutorial_analytics_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'api-submit',
      'page'   => 'documentation',
      'target' => '[data-tab="resources"]',
      'title'  => __('tutorial_api_submit_title'),
      'desc'   => __('tutorial_api_submit_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
    ],
    [
      'id'     => 'complete',
      'page'   => 'home',
      'target' => '.home-stats-grid',
      'title'  => __('tutorial_complete_title'),
      'desc'   => __('tutorial_complete_desc'),
      'pos'    => 'bottom',
      'arrow'  => true,
      'final'  => true,
    ],
  ],
];
